### PR TITLE
Add design

### PR DESCRIPTION
**Pull request by Satoshi-Sh**
Hi Ahmed,

I changed the design of Yoyogi a little bit. The main difference is that I removed y scroll bar from the window.  Hope you like the change.

### CODE REVIEW

**Comment by fasiha** [comment]
Thank you for this!!! I'm super-grateful and these look fantastic! For reference, below are screenshots, before and after—I love the new look!!

The one comment I have is, after login, the top bar is white even in dark mode, and it looks quite jarring (~bottom-most~ second-to-last image). Would it be possible for you to do your styling magic and make dark mode top bar look better?

## Before

### Login
Screenshot 2023-05-10 at 8 15 29 PM

### Logged in
Screenshot 2023-05-10 at 8 15 34 PM

## After

### Login, wide and narrow (dark mode)
Screenshot 2023-05-10 at 8 13 23 PM

Screenshot 2023-05-10 at 8 13 28 PM

### Logged in, dark mode and light mode

Screenshot 2023-05-10 at 8 14 27 PM

Screenshot 2023-05-10 at 8 14 43 PM

**Comment by Satoshi-Sh** [comment]
Screenshot from 2023-05-11 09-20-44

Thanks for the advice. I usually don't use dark mode.  Changed the color of the header for the dark mode. I also replaced min-width with width since threads with short toots get shorter width.

I try to make <sup> works in a flexbox to keep your original design, but I couldn't find out the way.

**Comment by fasiha** [comment]
@Satoshi-Sh ohh interesting, I think only Chrome allows media queries inside CSS blocks, in Firefox and Safari dark mode, it looked the same 😅. Here's a simple solution though:
```patch
diff --git a/styles/components.module.css b/styles/components.module.css
index e8aa71f..8c980ca 100644
--- a/styles/components.module.css
+++ b/styles/components.module.css
@@ -31,7 +31,9 @@
   justify-content: center;
   align-items: center;
   height: 5em;
-  @media (prefers-color-scheme: dark) {
+}
+@media (prefers-color-scheme: dark) {
+  .header {
     background: #18191a;
   }
 }
```
Can I trouble you one more time to make this change 😇? (I could also open a PR to your PR, or you could add me as a collaborator to your fork, but maybe it's easier to do it this way 🥹.)

I didn't know much about the accessibility impact of dark mode vs light mode, but began learning about it from Mastodon actually, for example https://mspsocial.net/@bright_helpings/105698480736999872 and https://social.chinwag.org/@mike/109372911699208566 it seems a lot of sites have dark mode designs without a light mode and that's a problem for some readers. Ever since learning about this I try to support both.

**Comment by Satoshi-Sh** [comment]
Just updated it as requested. That's interesting each browser works a little bit differently.

**Comment by fasiha** [comment]
> Just updated it as requested. That's interesting each browser works a little bit differently.

You're right that there's often considerable browser-to-browser variability, but from what I understand, media queries are definitely top-level, per [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/@media#syntax):

> The @media at-rule may be placed at the top level of your code or nested inside any other [conditional group at-rule](https://developer.mozilla.org/en-US/docs/Web/CSS/At-rule#conditional_group_rules).

I'm a bit surprised Chrome chose to handle this 😅!

Real apps will use tools like Playwright to run end-to-end tests on a variety of browsers (I got to see a little bit of how this worked when I worked with Project Jupyter, each PR and each release is tested on GitHub CI, all major browsers, all major operating systems 🤯). For me, I just test manually and hope my users forgive me if I overlook something 😅

Thank you again!! Merged! Live on https://fasiha.github.io/yoyogi/ 💖🚀!

**Pull request merged**
